name            = "cors-proxy-worker"
main            = "index.js"
compatibility_date = "2025-05-06"

account_id      = "${CF_ACCOUNT_ID}"
zone_id         = "${CF_ZONE_ID}"
workers_dev     = false
route           = "proxy.tothyoit.com/*"
