name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers

    steps:
      # ১) কোড চেকআউট
      - name: Checkout repository
        uses: actions/checkout@v3

      # ২) Worker ডিপ্লয়
      - name: Publish Worker to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}     # আপনার API Token
          accountId: ${{ secrets.CF_ACCOUNT_ID }}   # আপনার Account ID
          workingDirectory: .                       # আপনার প্রোজেক্ট ডিরেক্টরি
          command: publish                          # Wrangler কমান্ড (publish)
