# .github/workflows/deploy.yml
name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ১) কোড চেকআউট
      - name: Checkout repository
        uses: actions/checkout@v3

      # ২) Node.js ইনস্টল (npx/Node নিশ্চিত করার জন্য)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # ৩) Worker ডিপ্লয়
      - name: Publish Worker to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: .
          wranglerVersion: '2.20.0'    # Wrangler CLI ভার্সন পিন
          packageManager: 'npm'        # npm ইউজ করতে বলুন
          command: 'publish'           # wrangler publish
